name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test-python:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No requirements file"

      - name: Run unit tests
        run: python -m unittest test_main.py
